### ISSUE TITLE
Crash Report in my list of mods when I add Thaumic Tinkerer

### ISSUE THREAD

**Issue by LittleWhispers** [Thaumic-Tinkerer/ThaumicTinkerer#773] opened 2015-08-07 04:09 UTC
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 8/6/15 9:02 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Duplicate enchantment id! class thaumic.tinkerer.common.enchantment.EnchantmentPounce and class net.mcft.copy.betterstorage.item.EnchantmentBetterStorage Enchantment ID:170
    at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
    at thaumic.tinkerer.common.enchantment.EnchantmentMod.<init>(EnchantmentMod.java:26)
    at thaumic.tinkerer.common.enchantment.EnchantmentPounce.<init>(EnchantmentPounce.java:8)
    at thaumic.tinkerer.common.enchantment.ModEnchantments.initEnchantments(ModEnchantments.java:56)
    at thaumic.tinkerer.common.core.proxy.TTCommonProxy.init(TTCommonProxy.java:103)
    at thaumic.tinkerer.common.ThaumicTinkerer.init(ThaumicTinkerer.java:95)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1098730912 bytes (1047 MB) / 1550319616 bytes (1478 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -Xms1024M -Xmx2048M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 48 mods loaded, 48 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{7.10.99.99} [Forge Mod Loader](minecraft_server.jar) 
    UCHI    Forge{10.13.4.1448} [Minecraft Forge](minecraft_server.jar) 
    UCHI    appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHI    CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHI    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHI    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHI    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHI    appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHI    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
    UCHI    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHI    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHI    betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) 
    UCHI    CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHI    BuildCraft|Core{7.0.20} [BuildCraft](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Silicon{7.0.20} [BC Silicon](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Transport{7.0.20} [BC Transport](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Builders{7.0.20} [BC Builders](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Robotics{7.0.20} [BC Robotics](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Energy{7.0.20} [BC Energy](buildcraft-7.0.20.jar) 
    UCHI    BuildCraft|Factory{7.0.20} [BC Factory](buildcraft-7.0.20.jar) 
    UCHI    ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHI    dimdoors{2.2.5-test9} [Dimensional Doors](DimensionalDoors-2.2.5-test9.jar) 
    UCHI    iChunUtil{4.2.1} [iChunUtil](iChunUtil-4.2.1.jar) 
    UCHI    Doors{4.0.1} [Doors](Doors-4.0.1.jar) 
    UCHI    EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UCHI    ExtrabiomesXL{3.16.2} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.2.jar) 
    UCHI    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHI    ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHI    ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHI    TConstruct{1.7.10-1.8.6a.build969} [Tinkers' Construct](TConstruct-1.7.10-1.8.6a.jar) 
    UCHI    ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    ExtraUtilities{1.2.9} [Extra Utilities](extrautilities-1.2.9.jar) 
    UCHI    Forestry{3.6.3.20} [Forestry for Minecraft](forestry_1.7.10-3.6.3.20.jar) 
    UCHI    rftl{1.7.10} [Rotten Flesh to Leather](Forge SSP SMP - Rotten Flesh 1.7.2 1.7.10.jar) 
    UCHI    GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.350.jar) 
    UCHI    GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.350.jar) 
    UCHI    Mystcraft{0.12.3.00} [Mystcraft](mystcraft-1.7.10-0.12.3.00.jar) 
    UCHI    PneumaticCraft{1.9.15-104} [PneumaticCraft](PneumaticCraft-1.7.10-1.9.15-104-universal.jar) 
    UCHI    Railcraft{9.6.1.0} [Railcraft](Railcraft_1.7.10-9.6.1.0.jar) 
    UCHI    StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) 
    UCHE    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164%281%29.jar) 
    UCHI    ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHI    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHI    McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHI    ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.3-303
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.1.0-161
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by WhitePhoenix0** [comment] 2015-08-08 15:24
Try changing your enchantment ids for the enchantments listed at the top.
Duplicate of https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/475

**Closed** 2018-06-19 01:46 UTC
