### ISSUE TITLE
Research Never Completes

### ISSUE THREAD

**Issue by kreezxil** [Thaumic-Tinkerer/ThaumicTinkerer#937] opened 2018-11-20 12:00 UTC
Not sure why #921 was closed.

I have it in my modpack World of Dragons which is good for 4k downloads weekly, seriously thinking about removing it.

The research never completes.

I am using version 1.12.2-5.0-353c71c  <--- are those extra 7 characters necessary?

**Comment by kreezxil** [comment] 2018-11-20 12:02
From my own issue tracker, not much data there, but we're tracking it. https://minecraft.curseforge.com/projects/world-of-dragons/issues/54

**Comment by wamc2017** [comment] 2018-11-20 12:12
Dupe of https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/921

**Comment by nekosune** [comment] 2018-11-20 12:43
It is a Alpha for a reason, the research for the current batch will be finished in a couple weeks, which is when I will release the first Beta version.

Please note in the future, Alpha versions will not be guaranteed to work in survival, only Beta versions are ones where everything should work in survival

**Comment by nekosune** [comment] 2018-11-20 12:44
I am finishing the tablet hopefully today, then will be adding the research, so my estimate is under a week - 2 weeks

**Comment by nekosune** [comment] 2018-11-20 12:44
@wamc2017  I know it is, for some reason the original author of #921 closed their issue, so it is good this one is here

**Comment by kreezxil** [comment] 2018-11-21 11:08
yeah @wamc2017 didn't you see that I reference 921 in my opening statement?

**Comment by hron84** [comment] 2019-01-01 13:16
@nekosune is there any info when research bug will fixed? I would really like to play with your mod, but if I cannot complete researches, TC does not allow me to craft stuffs... 😞

**Comment by iComputerfreak** [comment] 2019-01-04 15:50
As a workaround you could use `/thaum research <Player> <Research>` to cheat the research.
e.g. `/thaum research iComputerfreak BLACK_QUARTZ`. You can see a list of all research names via `/thaum research list`.

Not a perfect solution but at least you can use the items in Survival then, until its fixed :)

**Comment by Xie-Long-0** [comment] 2019-01-10 08:42
I have the same issue. When I click Completion button, it still shows completing.

**Comment by RonRicoSuave** [comment] 2019-01-26 03:38
To add to this, after manually adding BLACK_QUARTZ with the command, research on the talisman of remedium completes correctly when I have those items.  But neither of the others do.  I wonder if it's an issue with the items which don't have a parent research item in that tree?

**Comment by Solverbolt** [comment] 2019-02-17 21:04
Issue still persists as of today. currently playing FTB Unlimited Reloaded

**Comment by TheCodex6824** [comment] 2019-04-01 23:56
I had the same issue with research not completing when I was trying to add research to an addon, I think the AUTOUNLOCK meta property is broken and stops research from actually being completable. Maybe try removing it?

**Comment by sharddragonite** [comment] 2019-04-10 01:10
> I had the same issue with research not completing when I was trying to add research to an addon, I think the AUTOUNLOCK meta property is broken and stops research from actually being completable. Maybe try removing it?
> 
> Edit: I had some time to try it out and removing AUTOUNLOCK from everything fixed it for me. I'll probably submit a PR soon.

Where did you find the meta property?

**Comment by TheCodex6824** [comment] 2019-04-10 17:20
In the research JSON (research folder in the assets folder) some of the entries have a "meta" list, AUTOUNLOCK would appear in there. Not all of the research had it.

**Comment by sharddragonite** [comment] 2019-04-10 17:40
Cool, thank you. I will see if that patches it for my server.

**Comment by Frikkle** [comment] 2019-04-29 18:12
@sharddragonite did you manage to fix this for your server?

**Comment by Kiefy** [comment] 2019-05-01 17:52
Didn't work for me.  applied to server and client.

**Comment by TheCodex6824** [comment] 2019-05-01 21:30
> Didn't work for me. applied to server and client.

@Kiefy I'm guessing you probably weren't on the latest version from github as I just had to fix something that crashed dedicated servers on that version. Give the very latest version a try with that fix - it looks like their were other research fixes before mine, so if your version doesn't have those then things probably won't work.

**Comment by Frikkle** [comment] 2019-06-20 18:28
@nekosune I noticed you merged #944; would that influence the status of this issue as well?

**Comment by nekosune** [comment] 2019-06-20 19:56
It does finish this issue too

**Closed by nekosune** 2019-06-20 19:56 UTC
Labels: bug, priority
