### ISSUE TITLE
Minecraft 1.7.10 Infused potions uncraftable

### ISSUE THREAD

**Issue by bigman52796** [Thaumic-Tinkerer/ThaumicTinkerer#671] opened 2015-02-17 05:48 UTC
It seems that I am unable to create any of the potions from imbued grains. My thaumonomicon says to throw in a grain into a crucible with 5 auram and 5 of the appropriate aspect. I have tested it with all of the 4 primal grains, but none of them work. I am using the FTB Infinity pack, v1.0.2, and they work on neither SSP or SMP.

**Comment by nekosune** [comment] 2015-02-17 10:53
I need version of TT, not the modpack version, as we can't spend time tracking down a specific version of a modpack just to find which version of our mod they use, when you can look it up a tony bit easier by looking at your mods folder :)

**Comment by bigman52796** [comment] 2015-02-17 14:31
Oops, sorry bout that :) Seems to be version 162

**Comment by nekosune** [comment] 2015-02-17 15:31
Please test with the latest at http://jenkins.nekokittygames.com:8080/job/Thaumic Tinkerer/

**Comment by belathus** [comment] 2015-02-21 03:56
I'm using build 466, and the crucible just spits the grain back out like it usually does with items that have no aspects. I realize the latest build is 468.

**Comment by belathus** [comment] 2015-02-22 02:13
Also, I should point out that vacuos seeds are dropping a bucket of energized glowstone in Wanderlust Reloaded. Also, all seeds drop wheat seeds and wheat when I break them. Wanderlust Reloaded has Hunger Overhaul installed if that is relevant (the whole right-click harvesting thing works on these seeds, but only drops wheat, which is why I think it may be relevant).

Actually, when I rebooted the server, the vacuos seeds stopped dropping the energized glowstone and started dropping water cans from Forestry. Weird.

Should I open this as a separate issue?

**Comment by nekosune** [comment] 2015-02-22 02:24
Will look into, however the wheat and seeds is likely hunger overhaul,

**Comment by belathus** [comment] 2015-02-22 14:44
After harvesting them a few more times, what the seeds are giving me seems somewhat random. They gave me a bucket energized glowstone at first, then water cans, then liquifacted coal, a clay bucket of water, and now resonant ender. Granted, they've always given me liquid.

Also, just to be sure, is it intended that the perditio seeds give a stack of sand and the ordo seeds give a stack of glass?

**Comment by nekosune** [comment] 2015-02-22 15:08
Those last two are apparently, I will take a look but more worried about why potions not working 



—

**Comment by belathus** [comment] 2015-02-22 15:19
Gotcha. Take your time!

**Comment by Middim** [comment] 2015-09-11 08:21
I was just wondering if there was any headway in resolving this?

I also notice that the potions do not show up in the Thaumatorium either, although I didn't know if this was intended.

I am using the Aug 17th #508 TT and tried it with only that and Thaumcraft 4.2.3.5 and still cannot get them to work in either the Crucible or the Thaumatorium.

**Closed** 2018-06-19 01:47 UTC
Labels: Needs Information
