### ISSUE TITLE
Cowl Of the Abyssal Depths - cannot be crafted.

### ISSUE THREAD

**Issue by OverlordDerp** [Thaumic-Tinkerer/ThaumicTinkerer#692] opened 2015-03-17 04:16 UTC
Using ThaumicTinkerer-2.5-1.7.10-470, with Fastcraft and Optifine if it has any bearing. The cowl cannot be crafted, even after checking every item ID and matching it appropriately from NEI, as well as the Thaumonomicon. Modtweaker has not changed this recipe in any way.

**Comment by Brycey92** [comment] 2015-03-17 20:06
I can confirm this issue. It also existed in 2.5-1.7.10-162.

**Comment by Brycey92** [comment] 2015-03-20 14:55
This appears to be a duplicate of #670.

**Comment by neilometer** [comment] 2015-05-06 02:10
Make sure the metadata on your potion of night vision is correct.  For example, 373:8230 will NOT work, but 373:8198 will.  I found the same thing with the leggings.  The fire resist potion had to match a specific metadata.  Luckily, the loot bags drop them fairly frequently.

**Comment by nekosune** [comment] 2015-05-06 02:56
Thanks to @neilometer  this will be fixed in next release, metadtaa problems are usually pretty easy to fix, but hard to diagnose sometimes

**Closed** 2018-06-19 01:47 UTC
